name: 'lingua'
version: '1.0.0'
profile: 'lingua'

model-paths: ["models"]

models:
  lingua:
    staging:
      +materialized: view      # staging jako VIEW (lekkie, zawsze swieze)
    marts:
      +materialized: table     # marty jako TABLE (szybkie do odpytywania)
