FROM apache/airflow:2.8.0-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    "apache-airflow-providers-databricks==6.3.0" \
    "dbt-duckdb==1.8.4" \
    "confluent-kafka[avro]==2.3.0" \
    "fastavro==1.9.4" \
    "pydantic>=2.0"

ENV PYTHONPATH=/opt/airflow
