FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
  streamlit>=1.30.0 \
  plotly>=5.0.0 \
  pandas>=2.0.0 \
  pyspark==3.5.0 \
  delta-spark==3.0.0

EXPOSE 8501

CMD ["streamlit", "run", "/app/app.py"]
